import { describe, it, expect } from 'vitest';
import { generateId, isValidId } from './id.js';

describe('generateId', () => {
  it('returns a valid UUID v4 string', () => {
    const id = generateId();
    expect(isValidId(id)).toBe(true);
  });

  it('generates unique IDs on successive calls', () => {
    const ids = new Set(Array.from({ length: 100 }, () => generateId()));
    expect(ids.size).toBe(100);
  });

  it('produces lowercase hex with correct format', () => {
    const id = generateId();
    // 8-4-4-4-12 format
    expect(id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/);
  });

  it('has version 4 in the correct nibble', () => {
    const id = generateId();
    // 13th hex char (index 14 accounting for hyphens) should be '4'
    expect(id[14]).toBe('4');
  });

  it('has correct variant bits', () => {
    const id = generateId();
    // 17th hex char (index 19 accounting for hyphens) should be 8, 9, a, or b
    expect(id[19]).toMatch(/[89ab]/);
  });
});

describe('isValidId', () => {
  it('accepts a valid v4 UUID', () => {
    expect(isValidId('550e8400-e29b-41d4-a716-446655440000')).toBe(true);
  });

  it('accepts IDs generated by generateId', () => {
    expect(isValidId(generateId())).toBe(true);
  });

  it('rejects empty string', () => {
    expect(isValidId('')).toBe(false);
  });

  it('rejects non-UUID strings', () => {
    expect(isValidId('not-a-uuid')).toBe(false);
    expect(isValidId('12345')).toBe(false);
  });

  it('rejects UUIDs with wrong version', () => {
    // version 1 UUID format
    expect(isValidId('550e8400-e29b-11d4-a716-446655440000')).toBe(false);
  });

  it('rejects UUIDs with wrong variant', () => {
    // variant bits set to 0 (first char of 4th group should be 8-b)
    expect(isValidId('550e8400-e29b-41d4-0716-446655440000')).toBe(false);
  });

  it('is case-insensitive', () => {
    expect(isValidId('550E8400-E29B-41D4-A716-446655440000')).toBe(true);
  });

  it('can be used to validate board route params', () => {
    // Simulates extracting a boardId from a URL like /board/:boardId
    const url = `/board/${generateId()}`;
    const boardId = url.split('/board/')[1]!;
    expect(isValidId(boardId)).toBe(true);
  });

  it('rejects the legacy "default" board ID', () => {
    expect(isValidId('default')).toBe(false);
  });
});
